# Generated by Django 5.2.5 on 2025-08-25 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0007_alter_category_options_alter_othercategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, default='', help_text='Примененный код купона', max_length=50, verbose_name='Код купона'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(help_text='Владелец корзины', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='Корзина, в которой находится товар', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Количество товара', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(help_text='Выбранный вариант товара', on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_cartitem',
        ),
    ]
