# Generated by Django 5.2.5 on 2025-08-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_reviewimage_review_review_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_images',
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.review'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews_images/'),
        ),
    ]
