# Generated by Django 5.2.5 on 2025-08-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_review_review_images_reviewimage_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_image', to='catalog.review'),
        ),
    ]
