# Generated by Django 5.2.5 on 2025-08-25 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_reviewimage_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='othercategory',
            options={'ordering': ['name'], 'verbose_name': 'Дополнительная категория', 'verbose_name_plural': 'Дополнительные категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'size', 'color'], 'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товаров'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Изображение отзыва', 'verbose_name_plural': 'Изображения отзывов'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Описание категории', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение категории', null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показывать ли категорию на сайте', verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения категории', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='othercategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othercategory',
            name='description',
            field=models.TextField(blank=True, help_text='Описание дополнительной категории', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='othercategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показывать ли категорию на сайте', verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Размеры товара (ДxШxВ)', max_length=100, verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показывать ли товар на сайте', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показывать ли товар в рекомендуемых', verbose_name='Рекомендуемый'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Показывать ли товар как новинку', verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена товара со скидкой', max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Краткое описание для списка товаров', max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вес товара в граммах', max_digits=6, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показывать ли вариант на сайте', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Уникальный артикул варианта', max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Одобрен ли отзыв модератором', verbose_name='Одобрен'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='Покупал ли пользователь этот товар', verbose_name='Подтвержденная покупка'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Описание изображения для SEO', max_length=255, verbose_name='Альтернативный текст'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории товаров', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL', unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='othercategory',
            name='name',
            field=models.CharField(help_text='Название дополнительной категории', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='othercategory',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL', unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Базовая цена товара', max_digits=10, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Основная категория товара', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание товара', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Главное изображение товара', null=True, upload_to='products/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Название товара', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_category',
            field=models.ForeignKey(blank=True, help_text='Дополнительная категория товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_products', to='catalog.othercategory', verbose_name='Дополнительная категория'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(help_text='Цвет товара', max_length=30, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение варианта товара', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена варианта товара', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(help_text='Основной товар', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(help_text='Размер товара', max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Количество товара на складе', verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Текст отзыва', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(help_text='Товар, к которому относится отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=5, help_text='Оценка товара от 1 до 5', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='Автор отзыва', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение к отзыву', null=True, upload_to='reviews_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(blank=True, help_text='Отзыв, к которому относится изображение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_image', to='catalog.review', verbose_name='Отзыв'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='catalog_category',
        ),
        migrations.AlterModelTable(
            name='othercategory',
            table='catalog_othercategory',
        ),
        migrations.AlterModelTable(
            name='product',
            table='catalog_product',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='catalog_productvariant',
        ),
        migrations.AlterModelTable(
            name='review',
            table='catalog_review',
        ),
        migrations.AlterModelTable(
            name='reviewimage',
            table='catalog_reviewimage',
        ),
    ]
